### ISSUE TITLE
Is this version of tensorflow required to be 2.0.0?

### ISSUE THREAD

**Issue by Xiaocong6** [Ecohnoch/tensorflow-cifar100#1]
hello, firstly thanks to your work.
and i want to ask 
is this version of tensorflow required to be 2.0.0?

**Comment by Finn-Fengming** [comment]
No, the version is tensorflow-gpu=1.11.0.

**Comment by Xiaocong6** [comment]
hi, I have encountered an error, 
RuntimeError: TensorLayer does not support Tensorflow version older than 2.0.0.
the version of tensorflow(CPU) is 1.13.1
What is the cause of this error?

**Comment by Finn-Fengming** [comment]
Maybe the new version of TensorLayer doesn't support tf-1.x. 
You can try the Tensorlayer-1.11.1. 
If this doesn't work, delete all codes about tensorlayer and try the[ pure tf resnet ](https://github.com/Ecohnoch/tensorflow-cifar100/blob/master/model/resnet50.py)

**Comment by Finn-Fengming** [comment]
Hi, I have updated most of the codes and maybe they could be helpful for you.

**Comment by Xiaocong6** [comment]
Thanks!!!
A little busy recently, I’ll try it soon.
You are so kind!
