### ISSUE TITLE
好奇作者

### ISSUE THREAD

**Issue by ming71** [Ecohnoch/tensorflow-cifar100#3]
在我的follower里面无意看到你，感觉很有意思。人大不文史类的吗，老哥你怎么还会搭博客，搞深度学习啊==震惊....

**Comment by ming71** [comment]
顺便想拜访一下你的博客发现gitpage好像404了，是转到个人站点了吗？

**Comment by Finn-Fengming** [comment]
哈？老哥可以了解一下人大信息学院，除了数据库领域很强外，DL方面在NLP上也作出过很多杰出贡献。
例如我两位师兄做过的一些：
1. [https://github.com/Embedding/Chinese-Word-Vectors](https://github.com/Embedding/Chinese-Word-Vectors)
2. [https://github.com/dbiir/UER-py](https://github.com/dbiir/UER-py)

博客应该是可以访问的吧...可能是受限域名服务器/代理服务器访问/安全证书相关的问题，理论上正常国内外的网络都能够访问。
