### ISSUE TITLE
Filling up shuffle buffer (this may take a while): 4298 of 50000？

### ISSUE THREAD

**Issue by henbucuoshanghai** [Ecohnoch/tensorflow-cifar100#6]
why？？？？？？？
tensorflow/core/kernels/data/shuffle_dataset_op.cc:135] Shuffle buffer filled.

**Comment by Finn-Fengming** [comment]
You can see the document about tf.data.TFRecordDataset.
This method is just to set a buffer for shuffling the data.
The value of buffer_size can be set by yourself.
