### ISSUE TITLE
测试batch，acc

### ISSUE THREAD

**Issue by henbucuoshanghai** [Ecohnoch/tensorflow-cifar100#7]
dataset_test = tf.data.TFRecordDataset('./trans/test.tfrecords')
    dataset_test = dataset_test.map(parse_test)
    dataset_test = dataset_test.shuffle(buffer_size=10000)
    dataset_test = dataset_test.batch(128)
    iterator_test = dataset_test.make_initializable_iterator()
next_element_test = iterator_test.get_next() 

avg_acc.append(acc_test_val)
                            except tf.errors.OutOfRangeError:
                                print('end test ', np.sum(avg_acc)/len(y_test))
now_test_acc = np.sum(avg_acc)/len(y_test)
测试batch是128，但是tfrecord提取测试机的时候，最后如果不能整除128，  测试集则不能被测试完    最后除以len(y_test)    所有数据  不对吧。。。

**Comment by Finn-Fengming** [comment]
抱歉回复晚了，你看我的acc_test并不是传统的reduce_mean，而是reduce_sum，含义是一个Batch中包含的1的个数，而不能整除128的情况也是无妨的，因为其中被预测为1的也加进去了，分母刚好是整体数据集的数量
